### ISSUE TITLE
ValueError: k-fold cross-validation requires at least one train/test split by setting n_splits=2 or more, got n_splits=0.

### ISSUE THREAD

**Issue by sugiyamath** [vecto-ai/vecto#72]
I want to evaluate my model by using JBATS_1.0(http://vecto.space/projects/jBATS/), like this:

```python
import vecto
import json
from vecto.embeddings import load_from_dir
from vecto.benchmarks.analogy.analogy import Analogy

path_model = "./plain_no_file_header/"
model = load_from_dir(path_model)

results = Analogy().run(model, "./JBATS_1.0")
with open("out.json", "w") as f:
    json.dump(results, f)
```

but ValueError occurred: 

```
INFO:vecto.embeddings:./plain_no_file_header/Detected VSM in plain text format
INFO:vecto.benchmarks.analogy.analogy:processing ./JBATS_1.0/.Rhistory
Traceback (most recent call last):
  File "run_eval.py", line 9, in <module>
    results = Analogy().run(model, "./JBATS_1.0")
  File "/opt/conda/lib/python3.7/site-packages/vecto/benchmarks/analogy/analogy.py", line 185, in run
    result_for_category = self.run_category(pairs)
  File "/opt/conda/lib/python3.7/site-packages/vecto/benchmarks/analogy/analogy.py", line 109, in run_c
ategory
    kfold = sklearn.model_selection.KFold(n_splits=len(pairs) // self.size_cv_test)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 419, in __init_
_
    super(KFold, self).__init__(n_splits, shuffle, random_state)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 284, in __init_
_
    " got n_splits={0}.".format(n_splits))
ValueError: k-fold cross-validation requires at least one train/test split by setting n_splits=2 or mor
e, got n_splits=0.
```

Could you tell me how to run it correctly?

**Comment by libofang** [comment]
Hi, sugiyamath

Sorry for this trouble.
I just run your code and get the same issue.
A quick solution would be delete the './JBATS_1.0/.Rhistory' file.

Bofang Li

**Comment by libofang** [comment]
> Hi, sugiyamath
> 
> Sorry for this trouble.
> I just run your code and get the same issue.
> A quick solution would be delete the './JBATS_1.0/.Rhistory' file.
> 
> Bofang Li

We have also made a new downloadable link in http://vecto.space/data/  you can download the corrected version (without .Rhistory file) of JBATS.
